### ISSUE TITLE
some files don't render correctly

### ISSUE THREAD

**Issue by mimoo** [anoma/specs#117]
https://specs.anoma.net/main/architecture/language/j-group/vampir/ir_design.html

<img width="1107" alt="Screen Shot 2022-11-12 at 5 06 29 PM" src="https://user-images.githubusercontent.com/1316043/201500676-193f505f-7fad-4c2e-b68d-04ae0bae64e6.png">

if I had to guess it's the spacing between the codeblocks and the text

**Comment by cwgoes** [comment]
Thanks - we need to clean up this repository - just as a note, for VampIR you can find the latest specs at https://github.com/anoma/vamp-ir

**Comment by cwgoes** [comment]
Should be fixed now.
