### ISSUE TITLE
Revisions to Spec Abstract

### ISSUE THREAD

**Issue by isheff** [anoma/specs#119]
# Overview
I think this abstract requires substantial revisions, both in terms of writing (saying clearly what you intend) and intent (proposed architecture of Anoma). I don't think it provides readers with a clear picture of what Anoma is, and to the best of my ability to judge, I'm not sure what you're proposing is a good choice. 

# Detailed Notes
## [Paragraph 1](https://github.com/anoma/specs/blob/194550e76aa6a866a754758009145f2d30cfd521/src/abstract.md?plain=1#L3})
- I'm worried that the term "[cybernetic](https://en.wikipedia.org/wiki/Cybernetics)," which technically refers to any system with a feedback loop between biological and "technological" components, conjures  ideas of [cyborgs](https://en.wikipedia.org/wiki/Cyborg) and [cybermen](https://en.wikipedia.org/wiki/Cyberman), which we probably don't want.
- I'm worried that the term "causal accounting" connotes [causal consistency](https://en.wikipedia.org/wiki/Causal_consistency), a database standard which is wholly unsuitable for accounting. 
- I'm worried that "create, merge, and verify ... histories" sounds a lot like Fork-Join consistency used in [Natacha Crooks'](https://www.cs.cornell.edu/lorenzo/papers/Crooks16Tardis.pdf) and [Milano's](https://www.cs.cornell.edu/andru/papers/gallifrey/snapl.pdf) work. This is also generally not suitable for accounting. Forks in these works allow, for instance, double spends, with no way to concretely know if some conflicting branch is out there somewhere. Do you want to bring Crooks and Milano in to talk about this? They're both currently at Berkeley, but I know them from Cornell. 
- I'm worried that ["distributed linear resource logic"](https://core.ac.uk/download/pdf/82254841.pdf) usually implies some global trust model: in a heterogeneous byzantine system, whether the linearity of a given resource is maintained can vary by observer. I'm not sure anyone has yet researched how to program a ["linear logic"](https://en.wikipedia.org/wiki/Linear_logic) in such a model. 
- I'm worried that "_entanglement_, a pairwise measure of the degree of a particular kind of relationship between two identities" is not a good definition. What are we trying to _express_ with entanglement? I have no intuition here. I realize that there can be "Different measures of entanglement", but by this definition, all kinds of seemingly unhelpful things are "entanglement," including:
  - physical distance between any pair of identities that correspond to real people or objects
  - hamming distance between cryptographic public keys
  - any measure if similarity between the purchasing habits of pairs of identities in a marketplace
## [Paragraph 2](https://github.com/anoma/specs/blob/194550e76aa6a866a754758009145f2d30cfd521/src/abstract.md?plain=1#L5)
- I don't know what it means to "provision" "causal accounting." In my head, to "provision" something is to delegate out who gets how much of it, and "causal accounting" is presumably an activity. These definitions do not match "the system can combine local information about local causal dependence and local agent preferences into a gestalt system model of causal and preference relations...".
- Again I'm worried that the term "causal accounting" connotes [causal consistency](https://en.wikipedia.org/wiki/Causal_consistency), a database standard which is wholly unsuitable for accounting. 
- Suddenly there are "preference relations"? What are these? Also, the term "causal and preference relations" makes it sound like these relations are the same type, which sounds suspect to me. 
- Consensus cannot "provide pairwise and relative measures of preference satisfaction as outputs which can be used for resource provisioning decisions in the future." That's the job of a market or constraint solver. Consensus can only decide arbitrarily between alternatives, such as orderings. 
- I think this paragraph misses the general purpose of consensus in a distributed database system (such as a blockchain), which is to provide total order, or at least [serializability](https://en.wikipedia.org/wiki/Serializability) over the operations, events, transactions, or whatever. This order can be made _consistent with_ some underlying [causal order](https://en.wikipedia.org/wiki/Causal_consistency), but provides a fundamentally different view of the system. 
  - One way to look at it would be that [causal consistency](https://en.wikipedia.org/wiki/Causal_consistency) gives an observer a large (usually exponential) number of possible [timeline prefixes](https://en.wikipedia.org/wiki/Temporal_logic) which "may have happened." Anyone who chooses a specific [timeline prefix](https://en.wikipedia.org/wiki/Temporal_logic) is performing [consensus](https://en.wikipedia.org/wiki/Consensus_(computer_science)). The extent to which anyone cares about their choice is a form of [Integrity](https://www.techtarget.com/whatis/definition/Confidentiality-integrity-and-availability-CIA). So for example, Tendermint runs a consensus system which has the _integrity_ property that it will always pick an extension of its previous choice of [timeline prefix](https://en.wikipedia.org/wiki/Temporal_logic) so long as more than 2/3 of its validators are honest. The purpose of Tendermint is to pick an ever-growing [timeline prefix](https://en.wikipedia.org/wiki/Temporal_logic) in the form of a chain of transactions: a blockchain. All other possible  transactions in the universe can form a causally-ordered DAG of many possible timelines, but Tendermint picks exactly one path through it. It does so fairly arbitrarily, the main constraint being that it uses only transactions people have published. (Unpublished but "possible" transactions can be seen as part of the infinite DAG of "possible" timelines.)
   - different consensus mechanisms could, in principle, pick different [timeline prefixes](https://en.wikipedia.org/wiki/Temporal_logic) consistent with the  [causal ordering](https://en.wikipedia.org/wiki/Causal_consistency) of published transactions. This corresponds to a disagreement over which order transactions happened in, including, for instance, double spends. Heterogeneous Paxos provides a convenient mechanism for forcing some consensus mechanisms with simlar-ish integrity properties to agree on consistent [timeline prefixes](https://en.wikipedia.org/wiki/Temporal_logic). 
   
## [Paragraph 3](https://github.com/anoma/specs/blob/194550e76aa6a866a754758009145f2d30cfd521/src/abstract.md?plain=1#L7)
- The definition "the system's fundamental unit of cryptographic identity is closed under composition, so the system can model relational topologies spanning arbitrary levels of individuality" does not match a commonly-used definition of [scale-free](https://en.wikipedia.org/wiki/Scale-free_network). 
- What does  "the system's fundamental unit of cryptographic identity is closed under composition" mean? What kinds of composition are we considering for identities? Why would we consider those and not some other kinds of composition? Why are we talking about this here?
- What is "economic distance?" [Doesn't that usually refer to the cost of transportation between physical locations](https://drpranabkrdas.home.blog/2020/05/16/concept-of-economic-distance-in-transport-geography/#:~:text=When%20the%20distance%20between%20two,goods%20considering%20the%20transport%20cost.)?
- Inverse power law of what? Graph degree? Is there a proof that random graphs with inverse power law degrees become fractal somehow? Is whatever graph we're talking about likely to be random? What are we talking about here? 
  - If Anoma is meant to represent "the economy," then while it's true that [fractals are common in economics](https://link.springer.com/referenceworkentry/10.1007/978-1-4419-7701-4_25#:~:text=Market%20price%20fluctuation%20was%20the,Fractals%20are%20everywhere%20in%20economics.) I don't know that it's true that "the economy" is "[a fractal](https://en.wikipedia.org/wiki/Fractal)."

## [Paragraph 4](https://github.com/anoma/specs/blob/194550e76aa6a866a754758009145f2d30cfd521/src/abstract.md?plain=1#L9)
- We'll need specific abstractions of cryptographic primitives and their information-theoretic assumptions.  This is a field I know very little about. I vaguely recall that cryptographic protocols don't always compose with the properties I would expect. Does the [Universal Composability](https://en.wikipedia.org/wiki/Universal_composability) framework help?
- There is a subtle difference between " The protocol architecture abstracts cryptographic primitives by their information-theoretic properties", which implies that a specific implementation could choose specific required primitives, and "implementations of particular primitives can be chosen and updated," which implies that implementations must themselves abstract over primitives, allowing for updates. Which are we saying?

## [Paragraph 5](https://github.com/anoma/specs/blob/194550e76aa6a866a754758009145f2d30cfd521/src/abstract.md?plain=1#L11)
No notes. 

## [Paragraph 6](https://github.com/anoma/specs/blob/194550e76aa6a866a754758009145f2d30cfd521/src/abstract.md?plain=1#L13)
- Provide a link to precisely the definition of "free" you want. I'm sure many websites have long treatises on many possible definitions of "free."

# What I Think You're Proposing
I'm going to try to rephrase what I think you're proposing Anoma to be. I doubt that my phrasing is better than yours, but it might clarify some of my confusion.

## [State](https://en.wikipedia.org/wiki/State_(computer_science)) and [Transactions](https://en.wikipedia.org/wiki/Transaction_processing)
Anoma specifies a notion of [transactions](https://en.wikipedia.org/wiki/Transaction_processing), each of which have 0 or more _input [states](https://en.wikipedia.org/wiki/State_(computer_science))_, and one _output [state](https://en.wikipedia.org/wiki/State_(computer_science))_. Each transaction's input states are the output states of referenced "prior" transactions. 

These states include collections of economic statements, such as who has what, and who wants what, and how much.

Anoma specifies a format for encoding hashes of states, which are probably encoded using a Merkle Tree or something. 

## Permissions
Portions of state can constrain later transactions. Each transaction must contain a _proof_ of some kind that its output state complies with the permission constraints of its inputs. These constraints can include things like 
- any transaction with this portion of state in any of its inputs must retain this portion of state in its output _unless_ it contains a statement signed by Alice.
- no descendant of this state may have an output state satisfying this predicate: (some arbitrary function here).
- any transaction with this portion of state in any of its inputs which also has another input in which a similar portion of its state (perhaps identified by a _key_) has a different value must include in its output a corresponding portion of state with the following value...
  - this would allow us to encode reconciliation for forked paths through the DAG, e.g. [CRDTs](https://arxiv.org/pdf/1805.06358.pdf) or even double spends (to an extent). 

## Open
Anyone can contribute a transaction at any time, dependent on any other transactions they've heard of, and share it with anyone who cares to listen. The only limits are cryptographically enforced in state permissions. 

## Causally Ordered
I have left vague here how one writes a transaction or specifies what its "priors" are, or proves that its output is consistent with the permissions of its inputs. You could, for instance, require that priors are specified as a list of hashes of encodings of previous transactions. I'm not sure if you actually want to do that. For instance, people might write transactions without knowing exactly what the inputs are, and then hand them off to a consensus engine, so that it can put them in a totally ordered chain, thus determining the input for each. The proofs associated with each transaction would need to be a little more flexible...

## [Consensus](https://en.wikipedia.org/wiki/Consensus_(computer_science))
A [consensus](https://en.wikipedia.org/wiki/Consensus_(computer_science)) system decides on a specific "current" transaction (and thus an output state), and guarantees that any future "current" transaction it picks will be a descendant of that transaction. It may even have other guarantees: for example, it might state that certain kinds of transactions will not appear in the causal history of any transaction it chooses. 

Each consensus system is characterized by its _integrity_: under what conditions will it maintain its guarantee? 

Different consensus systems can choose different current transactions. These do not have to be consistent: Alice consensus might pick transaction `a`, and Bob consensus might pick transaction `b` despite the fact that no possible transaction can have both `a` and `b` in its ancestry. This would be an example of irreconcilable differences. 

I'd note that Hetereogeneous Paxos allows 2 different consensus systems to guarantee that they agree under some conditions. 

## Identity
The only identities that matter are cryptogrphic, including public keys or perhaps hash identifiers. We have a notion of "conjunctive" and "disjunctive" identities as well. These identities can be used in permissions statements. 

# Why what I think you're proposing is very difficult
I'm not sure that these kind of permissions are a good way to express everything everyone wants to express, but even if they are, they are extremely hard to enforce. Naively, in order to determine if a state is "valid," we would have to read all of its (transitive) ancestors, and check all of their transactions' proofs.  These could be arbitrarily many, and may be arbitrarily difficult to compute or prove. We could accelerate this if the proofs were [rollups](https://ethereum.org/en/developers/docs/scaling/zk-rollups/), so each transaction proves not only that its output is valid given its inputs, but that its inputs are valid as well. However, even with rollups, it would be difficult for, say, a consensus protocol to know if one transaction is a descendant of another, unless the history of transactions is itself stored in state anyway. 

I'm worried that the permissions necessary to express some of the things you might want are less elegant / involve storing more state than you might think. For example, suppose Alice has a bank account stored in state `a` and starts with `$0`. In state `b`, Bob gives her $1, so her state goes to `$1`. In _concurrent_ state `c`, Carol gives her $1, so her state goes to `$1`. A later transaction `d` with both `b` and `c` as inputs might naively output Alice's state as `$1`, if her permissions merely check that inputs have the same dollar amount for Alice's bank account. Since 2 different people have each given Alice $1, we probably want `d` to store Alice's account as $2. The (naive) correct alternative would be for her account to track a specific, ever-growing set of deposits, and for outputs to require a union of the deposits from inputs. This would, however, require storing a lot more information. In contrast, systems which rely on serializability do not need to track this kind of thing. 

Some of the example permissions involve checking future states to ensure they retain the same (or some related) permission. Writing code to produce (or at least check for) itself (a [quine](https://en.wikipedia.org/wiki/Quine_(computing))) is possible, but extremely inelegant.  

We've also said nothing here about storage: we could easily forget about transactions, and we haven't set up any framework for quantifying when that can or should happen. Most importantly, we don't want a consensus system to forget permission constraints it's supposed to be checking. 

This system also says nothing about what to do with "irreconcilable differences," meaning situations where no possible transaction can be a descendant of transactions `a` and `b`. We have no quantification for how much of an "integrity failure" each irreconcilable difference is, so we can't say things like "this transaction only cares about this part of the state, so we're just going to consider that this other part of the state has failed, and move on with our lives."

# An Example of an Alternative Model
We could instead partition state into a portion for each consensus system, where that consensus system's statement about its partition is final. By attaching permissions to partitions of state rather than values in state, we don't have to read an entire history of values to know if a new operation is acceptable. Each partition is a serializable state machine which can be programmed largely independently, with well-defined integrity. We can even make new partitions using various combinations of existing partitions:
- this partition requires commitments from both consensus system `a` and `b`
- this partition requires commitments from 2 out of 3 of consensus systems `a`, `b`, and `c`.

Transactions involving multiple partitions are naturally perilous, but can have certain guarantees under some conditions. We can even characterize each piece of state with which systems are allowed to influence it, under what circumstances. This gets into [information flow control](https://www.cs.cornell.edu/andru/papers/jfabric/jfabric.pdf), which is a whole thing. 

We could even have an additional, "causally consistent" partition, where only specific operations are "safe," but we'd have to think carefully about how this works. 

I don't know that this is a good idea for a model, but it does provide some contrast with the model I think you're proposing. 

Sincerely,
- Isaac Sheff

**Comment by cwgoes** [comment]
Thanks!

I'm going to start in reverse order, and this may take me a few comments (due to piecemeal intermingling with some other work).

> We could instead partition state into a portion for each consensus system, where that consensus system's statement about its partition is final. By attaching permissions to partitions of state rather than values in state, we don't have to read an entire history of values to know if a new operation is acceptable. Each partition is a serializable state machine which can be programmed largely independently, with well-defined integrity. We can even make new partitions using various combinations of existing partitions:

I think this _is_ what I am proposing, although perhaps it is not what the abstract conveys. In the resource logic DAG - which is the first part of the protocol stack where we care about linearity - resources (from which state is computed) each have a list of controllers, and the latest controller's signature is required for a transaction consuming that resource to be valid ([here](https://specs.anoma.net/main/architecture/layers/logical-dags/resource-logic-dag.html#transactions) under "_final_"). Controllers, which may be instantiated by consensus algorithms, may totally order their signed messages (or, as a looser requirement, totally order possibly-conflicting signed messages), in which case I believe this instantiates the model you describe. The only difference here is that resources carry a "history" of past controllers - this allows for an order-of-resolution in case of conflicts for resources issued by some origin consensus system but later double-spent by another. It's roughly the same idea as [IBC uses](https://github.com/cosmos/ibc/tree/main/spec/app/ics-020-fungible-token-transfer), but built into the resource model instead of as a protocol layered on top.

> I'm not sure that these kind of permissions are a good way to express everything everyone wants to express, but even if they are, they are extremely hard to enforce. Naively, we would have to keep track of every ancestor of any "current" transaction, and check all of their permissions constraints. These could be arbitrarily many, and may be arbitrarily difficult to compute or prove.

I agree, we cannot have transactions be dependent on arbitrary computations over all of their ancestors - although I think it is fine to have them be dependent on incremental computation over all of their ancestors (i.e., state).

> Some of the example permissions involve checking future states to ensure they retain the same (or some related) permission. Writing code to produce (or at least check for) itself (a [quine](https://en.wikipedia.org/wiki/Quine_(computing))) is possible, but extremely inelegant.

Yes, this is a reason for the "balance" check in resource logic transactions ([here](https://specs.anoma.net/main/architecture/layers/logical-dags/resource-logic-dag.html#transactions)) - alternatively phrased, _every_ resource type involved in a transaction is both created and destroyed.

(will continue later...)

**Comment by cwgoes** [comment]
Abstract since updated.
