### ISSUE TITLE
Build circuits on top of Sapling or Orchard design?

### ISSUE THREAD

**Issue by joebebel** [anoma/specs#34]
Opening a separate issue from heliaxdev/spec#17 because this is a complicated question by itself.

Currently the MASP is based on the Sapling protocol/circuit/design over BLS12-381, using the Groth16 proving system. The advantages of this are small proof size, efficient verifiation, and also extensive existing analysis of the original Sapling design and code. 

We are currently evaluating moving MASP (built on Sapling) to the PLONK proving system over BLS12-381. There's some drawbacks in proof size, but more flexibility in reduced trusted setup requirements, and opportunities for optimization (e.g. plookup for blake2s) 

However, we should also evaluate building everything on top of the newer Orchard protocol using the PLONK/inner product argument proving system over the non-pairing "Pasta" cycle. 

Pro/con lists:

Sapling pros:
1. MASP based on Sapling is already implemented, tested, and audited
2. We already have strong understanding of Sapling protocol
3. Good work so far in converting MASP to PLONK
3. KZG based proving system is quite efficient (~500-600 byte proofs)
4. Reuse of existing trusted setup for new MASP circuits

Sapling cons:
1. No further development on Sapling from the Zcash side - all work will be on Orchard
2. Eventually MASP has to merge Zcash updates, or else independently implement all new features, and the more features we add, the more difficult it becomes
3. Integrating validity predicates is a bit of a mess - e.g. non-native arithmetic implementation questions, etc. This is because checking private validity predicates is essentially just one layer proof composition of some kind.

Orchard pros:
1. Much easier to pull features from upstream
2. Halo 2 (or better) is the future technology that everyone will migrate to eventually - might as well do it now
3. Eventually Zcash may have Zcash Shielded Assets, allowing a unified multi-asset codebase
4. Probably allows sooner deployment of recursion/composition for scalability, than if we plan to switch to Orchard later
5. Theoretically easier to integrate validity predicates because of the non-pairing curve cycle.

Orchard cons:
1. Much larger proof sizes (we estimated 4kB) that must be accommodated until true recursion or composition are deployed
2. We have to figure out how to reconcile Zcash PLONK and Dusk PLONK, which we've put our own effort into
3. We also have extensive work on (for example) plookup blake2s. However, it is possible that such effort can be reused even with Orchard
4. Some minor incremental effort to understand the Orchard protocol and codebase and re-implement the MASP on top of Orchard
5. Some minor issues with allowing validity predicates with large circuit size. Unlike KZG based VP, we probably have to choose a maximum size circuit to allow for VP and everyone pays that cost.

Since I don't believe the correct choice is obvious, I'd like to hear from everyone what they think (and also ask questions or concerns)

**Comment by cwgoes** [comment]
Closing as out-of-date - recent work can be found in anoma/taiga :smile:
