### ISSUE TITLE
Dogfooding

### ISSUE THREAD

**Issue by cwgoes** [anoma/specs#56]
We should put our money where our mouth is and start experimenting with some existing decentralised technologies in cases where we care about the properties they provide, such as censorship resistance (important for the Anoma specs). 

For example:
- This specification repo could be hosted on [Radicle](https://docs.radicle.xyz/docs/what-is-radicle.html) and mirrored to Github.
- We could write blog posts using [Mirror](https://mirror.xyz/) (though it seems to have a lot of NFT-related features now which I'm not sure we need). 
- The Anoma websites could be (at least accessible) on the [Beaker browser](https://beakerbrowser.com/)
- Socials could happen on [Diaspora](https://diasporafoundation.org/) and/or [Mastodon](https://joinmastodon.org/).

These platforms aren't yet popular, so we shouldn't limit Anoma to them - but they are likely populated by communities with whom we share some aims, and we should try to test their products and see how we can help each other out.

**Comment by awasunyin** [comment]
1. Radicle seems worthwhile trying out - how much operational overhead will this add to the process of writing and updating specs?
2. Mirror seems really odd - it looks like it's a decentralized version of Medium + allows co-authoring but what's up with the front page? It might be worthwhile trying it @AMiles14 - probably for some certain classes of articles.
3. We could check this going forward with the dev team(s) that will be implementing the websites going forward but we should absolutely not block our releases that are prioritizing most popular browsers (Chrome, Firefox, Safari) on this. @ChrisHoltDesign could you check if Breaker compatibility is possible with Lucian later on?
4. @AMiles14 & @gabriella-fw we should check out Diaspora & Mastodon

**Comment by ChrisHoltDesign** [comment]
Yeah sure, I'll make sure to bring it up when we chat with Lucian again next week!

**Comment by AMiles14** [comment]
Great ideas. I think both Diaspora and Mastodon can provide some great reach toward our ideal target audience. I will look into both platforms (also I have been looking at marketing on Brave as something we could do down the line). I'll also take a look at mirror :)
