### ISSUE TITLE
Rendering issue with katex

### ISSUE THREAD

**Issue by james-chf** [anoma/specs#91]
Some code blocks may not render properly e.g. in `ethereum-bridge.md` this block

```
/eth_block/$block_hash/header : Vec<u8>
/eth_block/$block_hash/messages : Vec<Vec<u8>>
/eth_block/$block_hash/seen_by : Vec<Address>
/eth_block/$block_hash/voting_power: u64
/eth_block/$block_hash/seen: bool
/eth_block/$block_hash/? : [u8; 32]
# not yet decided
/eth_block/$block_hash/merkle_proofs : Vec<Vec<u8>>
```

is rendered with the `$` replaced by HTML tags (https://specs.anoma.net/master/architecture/interoperability/ethereum-bridge.html)

![specs anoma net_master_architecture_interoperability_ethereum-bridge html (1)](https://user-images.githubusercontent.com/102907518/169272236-aa444547-8a23-460f-be7d-160b10f719ba.png)

**Comment by james-chf** [comment]
https://github.com/lzanini/mdbook-katex/issues/9

**Comment by cwgoes** [comment]
Should we just fork the upstream and fix this?

**Comment by james-chf** [comment]
Yeah we could fork it and fix it ourselves, at a glance it doesn't look like there is an alternative package we could use (https://github.com/lbeckman314/mdbook-latex hasn't been updated in a couple of years)

**Comment by james-chf** [comment]
NB: not fixed yet (or has regressed)

Screenshot from https://specs.anoma.net/master/architecture/interoperability/ethereum-bridge.html today

<img width="769" alt="Screenshot 2022-06-09 at 11 03 06" src="https://user-images.githubusercontent.com/102907518/172809101-8586008a-e5d5-420b-92df-1f61bbbdb879.png">

**Comment by james-chf** [comment]
I updated the CI to cache based on a hash of the Makefile (https://github.com/anoma/specs/blob/master/.github/workflows/deploy-master.yml#L25), I'm getting this rendering issue as well locally unfortunately

**Comment by cwgoes** [comment]
This has been fixed upstream; we should just need to update.
